In [2]:
import numpy as np

a = np.array([1,2,3,4,5,6])
b = np.array((2,3,4,5,6,7))

print(a)
print(b)

type(a)
type(b)

[1 2 3 4 5 6]
[2 3 4 5 6 7]


numpy.ndarray

In [14]:
d = np.array([[1,2,3],[4,5,6]])
print(d.ndim)
print(d[1,2])
print(d)

2
6
[[1 2 3]
 [4 5 6]]
