In [7]:
import numpy as np


hi = np.array([1,2,3,4,5,6,7])
print(hi)
print(type(hi))


[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [8]:
hi = np.array((1,2,3))
print(hi)

[1 2 3]


In [14]:
#import numpy as np
#learning 1d ,2d and 3d 
h = np.array(40)
x = np.array([[1,2,3,4],[5,6,7,8]])
print(h)
print(x)
print(type(h))
print(type(x))
# for 3d 

y = np.array([[[1,2,3],[4,5,6],[7,8,9],[12,13,14]]])
print(y)


40
[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [12 13 14]]]


In [17]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 2, 6],
    [7, 8, 2],
    [1,2,3],
    ["boom","baam","hehe"]
])

print(arr)


[['1' '2' '3']
 ['4' '2' '6']
 ['7' '8' '2']
 ['1' '2' '3']
 ['boom' 'baam' 'hehe']]


In [10]:
x = np.random.randint(20,30)
print(x)


28


In [15]:

a = np.arange(5)
print(a)

x = np.random.permutation(10)
print(x)


[0 1 2 3 4]
[9 0 2 6 5 4 3 7 1 8]
